---
title: "Analysis"
author: "Armelle Duston"
date: "2024-02-07"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libaries
```{r}
library(tidyverse)
library(ggplot2)
library(GGally)
library(leaps)
library(emmeans)
library(lme4)
library(car)

```

## Import Data
```{r}

wideData <- read.csv('clean_df_wide.csv')
longData <- read.csv('clean_df_long.csv')

# make categorical variables categorical 
wideData$site <-  as.character(wideData$site)
wideData$viewcat <-  as.character(wideData$viewcat)
wideData$setting <-  as.character(wideData$setting)
wideData$ID <-  as.character(wideData$ID)

longData$site <-  as.character(longData$site)
longData$viewcat <-  as.character(longData$viewcat)
longData$setting <-  as.character(longData$setting)
longData$ID <-  as.character(longData$ID)

subset_let <- wideData[c('ID', 'site', 'sex', 'age', 'setting', 'viewcat', 'encour', 'peabody', 'prelet', 'let_diff_pct')]
subset_form <- wideData[c('ID', 'site', 'sex', 'age', 'setting', 'viewcat', 'encour', 'preform', 'peabody','form_diff_pct')]
subset_numb <- wideData[c('ID', 'site', 'sex', 'age', 'setting', 'viewcat', 'encour', 'prenumb', 'peabody','numb_diff_pct')]

  
```

## Try some linear models
```{r}

let_fit0 <- lm(let_diff_pct ~ . , data = subset_let)
form_fit0 <- lm(form_diff_pct ~ . , data = subset_form)
numb_fit0 <- lm(numb_diff_pct ~ . , data = subset_numb)

step(let_fit0, trace = FALSE)
step(form_fit0, trace = FALSE)
step(numb_fit0, trace = FALSE)

```


## Linear Models
```{r}
let_lm <- lm(let_diff_pct ~ site + age + viewcat + prelet, data = subset_let)
form_lm <- lm(form_diff_pct ~ site + age + viewcat + preform , data = subset_form)
numb_lm <- lm(numb_diff_pct ~ site + age + viewcat + prenumb, data = subset_numb)

Anova(let_lm)
Anova(form_lm)
Anova(numb_lm)

# summary(let_lm)
# summary(form_lm)
# summary(numb_lm)

let_means <- emmeans(let_lm, ~viewcat, adjust = 'HSD')
let_means
plot(let_means, comparisons=T)

form_means <- emmeans(form_lm, ~viewcat, adjust = 'HSD')
form_means
plot(form_means, comparisons=T)

numb_means <- emmeans(numb_lm, ~viewcat, adjust = 'HSD')
numb_means
plot(numb_means, comparisons=T)

# make sure effect sizes are not tiny
effectsize(let_lm)
effectsize(form_lm)
effectsize(numb_lm)

par(mfrow=c(2,2))
plot(let_lm)
par(mfrow=c(2,2))
plot(form_lm)
par(mfrow=c(2,2))
plot(numb_lm)

```


Which test does the best?
```{r}
fit2 <- lm(diff_pct ~ which_test + site + viewcat, data = longData)
Anova(fit2)
summary(fit2)

whichtest_means <- emmeans(fit2, ~which_test, adjust = 'HSD')
plot(whichtest_means, comparisons=T)

# viewcat_means <- emmeans(fit2, ~viewcat, adjust = 'HSD')
# plot(viewcat_means, comparisons=T)
# 
# site_means <- emmeans(fit2, ~site, adjust = 'HSD')
# plot(site_means, comparisons=T)

par(mfrow=c(2,2))
plot(fit2)

```

Mixed effects model for which test is best?
```{r}

mixed_model <- lmer(diff_pct ~ which_test*viewcat + which_test*site + (1|ID), data = longData)
Anova(mixed_model)
summary(mixed_model)

mixed_model_means <- emmeans(mixed_model, ~which_test|viewcat, adjust = 'HSD')
plot(mixed_model_means, comparisons=T)
summary(mixed_model_means)
pairs(mixed_model_means)

mixed_model_means2 <- emmeans(mixed_model, ~which_test|site, adjust = 'HSD')
plot(mixed_model_means2, comparisons=T)


#likelihood ratio test to see if mixed model is needed
unmixed_model <- lm(diff_pct ~ which_test*viewcat + site, data=longData)

G2 = -2 * logLik(unmixed_model) + 2 * logLik(mixed_model)
pchisq(as.numeric(G2), df=1, lower.tail=F)

# make sure effect sizes are not tiny
effectsize(mixed_model)

plot(mixed_model)
res_mm <- residuals(mixed_model)
qqnorm(res_mm)
qqline()

### UNFINISHED - NEED TO PLOT RANDOM EFFECT RESIDUALS QQPLOT ##

```

Mixed effects model three way interaction...
```{r}

mixed_model2 <- lmer(diff_pct ~ which_test*viewcat*site + (1|ID), data = longData)
Anova(mixed_model2)
summary(mixed_model2)

mixed_model_means <- emmeans(mixed_model2, ~which_test|viewcat*site, adjust = 'HSD')
plot(mixed_model_means, comparisons=T)
summary(mixed_model_means)
pairs(mixed_model_means)

# make sure effect sizes are not tiny
effectsize(mixed_model2)

plot(mixed_model2)

```

